name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]  # すべてのブランチからのPRに対応

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install -e ".[all]"
    
    - name: Lint with Ruff
      run: ruff check .
      
  test:
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install -e ".[all]"
    
    - name: Test with pytest
      run: pytest -q tests/
    
    - name: Test run with example.com
      run: |
        python -m fetchmd run https://example.com --out out
        # 出力ファイルが存在するか確認
        find out/example.com -name "*.md" -type f | grep .