name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]  # すべてのブランチからのPRに対応

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
        
    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[all]"
    
    - name: Lint with Ruff
      run: |
        source .venv/bin/activate
        make lint
      
  test:
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    
    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[all]"
    
    - name: Test with pytest
      run: |
        source .venv/bin/activate
        make test
    
    - name: Test run with example.com
      run: |
        source .venv/bin/activate
        # URL変数を明示的に設定してmake runを実行
        make run URL="https://example.com"
        # 出力ファイルが存在するか確認
        find out/example.com -name "*.md" -type f | grep .